### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [JakubBrom/RasterScatterplot#1]
The functionality described in the About is similar to other plugins, in particular:
http://plugins.qgis.org/plugins/rasterdataplotting/
Please clarify how the plugin is actually different from that one.
Also, please consider merging your work into this one.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by JakubBrom** [comment]
Thanks a lot for the comments. Plugin RasterDataPlotting is realy new. I tried it. RasterDataPlotting plugin is good tool for raster data exploration in my opinion. My plugin is more simple. Against the RastarDataPlotting my plugin provides basic linear regression analysis of rasters which is usable e.g for comparison of results from calculation of (bio)physical features. Researchers need in some cases quick overview about their data relationship, not scatterplot only. A difference is mostly in way and reason of usage. Merging of my plugin with RasterDataPlotting is good idea for far future:-)

**Comment by pcav** [comment]
Thanks a lot for your clarification. I'm sorry to insist, but in my experience it is far easier to merge the work before publishing than after that.
May I ask you to contact the author of the other plugin and explore jointly the opportunity for a merge? I'd be happy of being included in the conversation.
Thanks for understanding.

**Comment by JakubBrom** [comment]
I agree. Please, could you ask Andreas Rabe for his opinion?

**Comment by pcav** [comment]
Done.

**Comment by janzandr** [comment]
Hi Jakub,

if you like I can add the functionality you mentioned. Quantitative correlation analysis (in terms of linear, logarithmic, exponential and power) between to vaiables perfectly fit to what I wanted to publish in one of the next releases anyway. I would plot the fitted function on top of the ScatterPlot and would also report performance measures (r^2, MAE, RMSE etc.).

I plan for a) an interactive mode, where only data currently visible in the MapCanvas is considered, and b) an analytical mode where ALL the data is considered.

Hope that is in your interest.

**Comment by JakubBrom** [comment]
Hi Andreas,
perfect, I agree with you. If I can help you please contact me.

Best regards
Jakub

**Comment by pcav** [comment]
So I can take this as a "yes, the new work can be merged into the published plugin?"
I would definitely appreciate this.
Thanks.

**Comment by JakubBrom** [comment]
Hi Paolo,
yes, if Andreas includes it to his plugin it will be perfect for users.

Thank you for your time,
Jakub

**Comment by pcav** [comment]
Success! thenks @JakubBrom @AndreasRabe

**Comment by janzandr** [comment]
FYI - I uploaded a new version that includes the curve fitting and correlation analysis:
https://plugins.qgis.org/plugins/rasterdataplotting/

**Comment by pcav** [comment]
Thanks @AndreasRabe !

**Comment by JakubBrom** [comment]
Andreas, thanks a lot!
